spring:
    application:
        name: restservice
    router:
        static-resources:
            default:
                enabled: true
                paths: classpath:public
                mapping: /**
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
